### ISSUE TITLE
Invalid character message does not disappear

### ISSUE THREAD

**Issue by omega1119** [jquintozamora/react-taxonomypicker-consume-es6#2]
Hi There,

When an invalid character is inputted, the message 'The value '' is invalid. It probably contains invalid characters or is too long. Parameter name: termLabel' is displayed, however, there is no way to get the message to disappear when a valid term is typed in. Is there a fix for this?

Thanks,
Simon

**Comment by jquintozamora** [comment]
Hi @omega1119 , 
I'm not able to reproduce that issue, could you please provide the exact journey to get into that state ? 

Thanks!

**Comment by omega1119** [comment]
Hi,

no problem, sorry should have described that initially. Type a character like ';' and then you'll see the message, and then after that type a valid term and select it. The message should still show.

**Comment by jquintozamora** [comment]
Hi @omega1119 , 

I tried to reproduce and I tike ; but I get this message and it disappear later:

![image](https://user-images.githubusercontent.com/12530031/36354757-1c7a5d78-14d1-11e8-8ba6-33e27600e7f9.png)

Are you using any specific source?

**Comment by jquintozamora** [comment]
Hi @omega1119 ,
I´ve updated react taxonomy picker to 0.0.40, now you can show the logs on demand

```js

    /**
     * Log Errors in console
     */
    logErrorsConsole?: boolean;

    /**
     * Log Errors in screen using div
     */
    logErrorsDiv?: boolean;
```

You can use these two properties to show the errors on console or screen.
